import { defineConfig } from 'vite-plus';

export default defineConfig({
  run: {
    // Package scripts must never be cached; tests, backup, restore, and the
    // weekly snapshot operation always execute fresh. No Vite Task
    // definitions exist for domain operations.
    cache: false,
  },
  fmt: {
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    semi: true,
    singleQuote: true,
    trailingComma: 'all',
    insertFinalNewline: true,
    sortPackageJson: true,
    ignorePatterns: [
      '**/AGENTS.md',
      '.env',
      '.env.*',
      'node_modules/**',
      'package-lock.json',
      'supabase/.temp/**',
      'supabase/.branches/**',
      'supabase/.link/**',
      '.tmp/**',
      'tmp/**',
      '.candidate/**',
      'candidate/**',
      'weekly-candidates/**',
      '.staging/**',
      'staging/**',
      'weekly-staging/**',
      'r2-download/**',
      'restore-*/**',
      'dump-*/**',
      'backups/**',
      'local-backups/**',
      'mds/**',
      'migration-history-data.sql',
      'database-data.sql',
      'data.sql',
      'data.sql.gz',
      'data.sql.gz.age',
      'data.sql.gz.part-*',
      '*.age',
    ],
  },
  lint: {
    // Only the explicitly migrated legacy ESLint policy runs: no implicit
    // Oxc/Unicorn/TypeScript/React plugin rule sets and no category rules.
    plugins: [],
    categories: {
      correctness: 'off',
    },
    env: {
      builtin: true,
    },
    ignorePatterns: [
      'node_modules/**',
      'package-lock.json',
      'supabase/.temp/**',
      'supabase/.branches/**',
      'supabase/.link/**',
      '.tmp/**',
      'tmp/**',
      '.candidate/**',
      'candidate/**',
      'weekly-candidates/**',
      '.staging/**',
      'staging/**',
      'weekly-staging/**',
      'r2-download/**',
      'restore-*/**',
      'dump-*/**',
      'backups/**',
      'local-backups/**',
      'mds/**',
      'migration-history-data.sql',
      'database-data.sql',
      'data.sql',
      'data.sql.gz',
      'data.sql.gz.age',
      'data.sql.gz.part-*',
      '*.age',
    ],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-empty': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
    },
    overrides: [
      {
        files: ['**/*.js'],
        rules: {
          'no-unused-vars': [
            'error',
            {
              argsIgnorePattern: '^_',
              caughtErrorsIgnorePattern: '^_',
            },
          ],
        },
        globals: {
          AsyncDisposableStack: 'readonly',
          DisposableStack: 'readonly',
          SuppressedError: 'readonly',
        },
        env: {
          es2024: true,
          node: true,
        },
      },
    ],
    options: {
      typeAware: false,
      typeCheck: false,
      maxWarnings: 0,
    },
  },
});
